### ISSUE TITLE
Outdated jQuery links on both examples

### ISSUE THREAD

**Issue by fusion2222** [rabbitmq/rabbitmq-web-mqtt-examples#2]
Old jQuery CDN link is not available anymore. It should be updated CDN link of newer jQuery version - `https://code.jquery.com/jquery-3.4.1.min.js`  

I already made commit locally, but looks like it is not possible to upload and create new branches and pull requests for strangers like me. so I at least created this Issue.

I tested if jQuery 3.4.1 is compatibile.

**Comment by lukebakken** [comment]
Hello @fusion2222 -

> I already made commit locally, but looks like it is not possible to upload and create new branches and pull requests for strangers like me

Please see the GitHub [help documents](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) for how to create a pull request. You will [fork this repository](https://help.github.com/en/articles/working-with-forks) to your GitHub account, push your changes, then open the pull request. Thanks!

**Comment by michaelklishin** [comment]
@fusion2222 thank you for reporting, `3.7.18` will ship with jQuery `3.4.1`.
